-- =============================================================================
-- V1: Criação do Schema de Banco de Dados PetGuardian conforme DER
-- =============================================================================

CREATE TABLE estado (
    id_estado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_estado VARCHAR(30) NOT NULL
);

CREATE TABLE cidade (
    id_cidade BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cidade VARCHAR(30) NOT NULL,
    id_estado BIGINT NOT NULL,
    CONSTRAINT fk_cidade_estado FOREIGN KEY (id_estado) REFERENCES estado(id_estado)
);

CREATE TABLE bairro (
    id_bairro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_bairro VARCHAR(30) NOT NULL,
    id_cidade BIGINT NOT NULL,
    CONSTRAINT fk_bairro_cidade FOREIGN KEY (id_cidade) REFERENCES cidade(id_cidade)
);

CREATE TABLE endereco (
    id_endereco BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep VARCHAR(9) NOT NULL,
    rua VARCHAR(150) NOT NULL,
    numero VARCHAR(5) NOT NULL,
    id_bairro BIGINT NOT NULL,
    CONSTRAINT fk_endereco_bairro FOREIGN KEY (id_bairro) REFERENCES bairro(id_bairro)
);

CREATE TABLE telefone (
    id_telefone BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_ddd VARCHAR(2) NOT NULL,
    num_tel VARCHAR(9) NOT NULL
);

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    id_telefone BIGINT NOT NULL,
    CONSTRAINT fk_usuario_telefone FOREIGN KEY (id_telefone) REFERENCES telefone(id_telefone)
);

CREATE TABLE usuario_endereco (
    id_usuario BIGINT NOT NULL,
    id_endereco BIGINT NOT NULL,
    PRIMARY KEY (id_usuario, id_endereco),
    CONSTRAINT fk_ue_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    CONSTRAINT fk_ue_endereco FOREIGN KEY (id_endereco) REFERENCES endereco(id_endereco)
);

CREATE TABLE raca (
    id_raca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_raca VARCHAR(30) NOT NULL
);

CREATE TABLE pet (
    id_pet BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    data_nasc DATE NOT NULL,
    sexo VARCHAR(1) NOT NULL,
    porte VARCHAR(10) NOT NULL,
    castrado BOOLEAN NOT NULL,
    id_raca BIGINT NOT NULL,
    CONSTRAINT fk_pet_raca FOREIGN KEY (id_raca) REFERENCES raca(id_raca)
);

CREATE TABLE usuario_pet (
    id_usuario BIGINT NOT NULL,
    id_pet BIGINT NOT NULL,
    respon_princ BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id_usuario, id_pet),
    CONSTRAINT fk_up_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    CONSTRAINT fk_up_pet FOREIGN KEY (id_pet) REFERENCES pet(id_pet)
);

CREATE TABLE status (
    id_status BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_status VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE tarefa (
    id_tarefa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(30) NOT NULL,
    pontos_tarefa INT NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    criacao TIMESTAMP NOT NULL,
    prazo TIMESTAMP NOT NULL,
    conclusao TIMESTAMP,
    id_usuario BIGINT,
    id_pet BIGINT NOT NULL,
    id_status BIGINT NOT NULL,
    CONSTRAINT fk_tarefa_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    CONSTRAINT fk_tarefa_pet FOREIGN KEY (id_pet) REFERENCES pet(id_pet),
    CONSTRAINT fk_tarefa_status FOREIGN KEY (id_status) REFERENCES status(id_status)
);

CREATE TABLE historico (
    id_hist BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_hist VARCHAR(30) NOT NULL,
    data_hist TIMESTAMP NOT NULL,
    id_pet BIGINT NOT NULL,
    CONSTRAINT fk_historico_pet FOREIGN KEY (id_pet) REFERENCES pet(id_pet)
);

CREATE TABLE trilha (
    id_trilha BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    id_pet BIGINT NOT NULL,
    CONSTRAINT fk_trilha_pet FOREIGN KEY (id_pet) REFERENCES pet(id_pet)
);

CREATE TABLE modulo (
    id_modulo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    tempo_conclusao VARCHAR(10) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    id_trilha BIGINT NOT NULL,
    CONSTRAINT fk_modulo_trilha FOREIGN KEY (id_trilha) REFERENCES trilha(id_trilha)
);

CREATE TABLE aula (
    id_aula BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    pontos_aula INT NOT NULL,
    dificuldade VARCHAR(20) NOT NULL,
    conteudo VARCHAR(1000),
    concluida BOOLEAN DEFAULT FALSE NOT NULL,
    id_modulo BIGINT NOT NULL,
    CONSTRAINT fk_aula_modulo FOREIGN KEY (id_modulo) REFERENCES modulo(id_modulo)
);
